// <auto-generated />
using System;
using Lab.Auth.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lab.Auth.Persistence.Migrations
{
    [DbContext(typeof(LabAuthDbContext))]
    [Migration("20260501231050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lab.Auth.Domain.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f5fb6ae-0561-4b65-92f5-5a6f0ca6c7d1"),
                            Biography = "Türk edebiyatının unutulmaz yazarlarından; toplumsal ve psikolojik derinliğiyle bilinir.",
                            BirthDate = new DateTime(1907, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sabahattin",
                            LastName = "Ali"
                        },
                        new
                        {
                            Id = new Guid("4a3f34c3-8a7c-4cbc-9c24-1ff717a8ba4a"),
                            Biography = "Nobel ödüllü yazar; İstanbul ve kimlik temalarıyla öne çıkar.",
                            BirthDate = new DateTime(1952, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Orhan",
                            LastName = "Pamuk"
                        },
                        new
                        {
                            Id = new Guid("8c3efaa3-3b94-4f17-bc2e-98e035a668cd"),
                            Biography = "Anadolu insanını ve idealizmi merkeze alan klasik romanların yazarı.",
                            BirthDate = new DateTime(1889, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Reşat Nuri",
                            LastName = "Güntekin"
                        });
                });

            modelBuilder.Entity("Lab.Auth.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b1c1b79-fc6e-4d3a-9e55-6f2e2e4b3c10"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sabahattin Ali’nin aşk ve yalnızlık temalarını işleyen klasiği.",
                            Isbn = "9789750805000",
                            PublicationYear = 1943,
                            PublisherId = new Guid("5f2c3d90-9a8e-4cf0-8ef7-7e2bc9a5a111"),
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = new Guid("0a81f345-62fb-4fbe-9cde-52d69f964bce"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Orhan Pamuk’tan İstanbul’da geçen modern bir aşk romanı.",
                            Isbn = "9789750809572",
                            PublicationYear = 2008,
                            PublisherId = new Guid("5f2c3d90-9a8e-4cf0-8ef7-7e2bc9a5a111"),
                            Title = "Masumiyet Müzesi"
                        },
                        new
                        {
                            Id = new Guid("e2c73d7f-5123-4b7f-9cf7-9f1d0105d01c"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reşat Nuri Güntekin’in idealist öğretmen Feride’nin hikâyesi.",
                            Isbn = "9789754700110",
                            PublicationYear = 1922,
                            PublisherId = new Guid("3a0d9b34-1c9a-4c57-8c31-8897e5b45ef2"),
                            Title = "Çalıkuşu"
                        });
                });

            modelBuilder.Entity("Lab.Auth.Domain.BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = new Guid("8b1c1b79-fc6e-4d3a-9e55-6f2e2e4b3c10"),
                            AuthorId = new Guid("2f5fb6ae-0561-4b65-92f5-5a6f0ca6c7d1"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("0a81f345-62fb-4fbe-9cde-52d69f964bce"),
                            AuthorId = new Guid("4a3f34c3-8a7c-4cbc-9c24-1ff717a8ba4a"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("e2c73d7f-5123-4b7f-9cf7-9f1d0105d01c"),
                            AuthorId = new Guid("8c3efaa3-3b94-4f17-bc2e-98e035a668cd"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Lab.Auth.Domain.BookCategory", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = new Guid("8b1c1b79-fc6e-4d3a-9e55-6f2e2e4b3c10"),
                            CategoryId = new Guid("2b5d5b82-2c80-4c03-8f4f-5a9b9d6b5c77")
                        },
                        new
                        {
                            BookId = new Guid("8b1c1b79-fc6e-4d3a-9e55-6f2e2e4b3c10"),
                            CategoryId = new Guid("35ef77fa-5f76-48ec-9f84-6cc81857232e")
                        },
                        new
                        {
                            BookId = new Guid("0a81f345-62fb-4fbe-9cde-52d69f964bce"),
                            CategoryId = new Guid("1c3a3f8e-b6d4-4ef8-8e7f-56ad52c57d8f")
                        },
                        new
                        {
                            BookId = new Guid("0a81f345-62fb-4fbe-9cde-52d69f964bce"),
                            CategoryId = new Guid("35ef77fa-5f76-48ec-9f84-6cc81857232e")
                        },
                        new
                        {
                            BookId = new Guid("e2c73d7f-5123-4b7f-9cf7-9f1d0105d01c"),
                            CategoryId = new Guid("2b5d5b82-2c80-4c03-8f4f-5a9b9d6b5c77")
                        },
                        new
                        {
                            BookId = new Guid("e2c73d7f-5123-4b7f-9cf7-9f1d0105d01c"),
                            CategoryId = new Guid("35ef77fa-5f76-48ec-9f84-6cc81857232e")
                        });
                });

            modelBuilder.Entity("Lab.Auth.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b5d5b82-2c80-4c03-8f4f-5a9b9d6b5c77"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Türk edebiyatının klasik kabul edilen eserleri.",
                            Name = "Klasik"
                        },
                        new
                        {
                            Id = new Guid("1c3a3f8e-b6d4-4ef8-8e7f-56ad52c57d8f"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uzun soluklu kurgu eserler.",
                            Name = "Roman"
                        },
                        new
                        {
                            Id = new Guid("35ef77fa-5f76-48ec-9f84-6cc81857232e"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yerel yazarların eserleri.",
                            Name = "Türk Edebiyatı"
                        });
                });

            modelBuilder.Entity("Lab.Auth.Domain.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Publishers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f2c3d90-9a8e-4cf0-8ef7-7e2bc9a5a111"),
                            Country = "Türkiye",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yapı Kredi Yayınları",
                            Website = "https://kitap.ykykultur.com.tr"
                        },
                        new
                        {
                            Id = new Guid("3a0d9b34-1c9a-4c57-8c31-8897e5b45ef2"),
                            Country = "Türkiye",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İş Bankası Kültür Yayınları",
                            Website = "https://isbankyayinevi.com"
                        });
                });

            modelBuilder.Entity("Lab.Auth.Domain.Book", b =>
                {
                    b.HasOne("Lab.Auth.Domain.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Lab.Auth.Domain.BookAuthor", b =>
                {
                    b.HasOne("Lab.Auth.Domain.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab.Auth.Domain.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Lab.Auth.Domain.BookCategory", b =>
                {
                    b.HasOne("Lab.Auth.Domain.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab.Auth.Domain.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lab.Auth.Domain.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Lab.Auth.Domain.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("Lab.Auth.Domain.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("Lab.Auth.Domain.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
